#!/bin/lua

-- @script simple client for hls-server (cpp)
--
-- @usage you need set host, port and name offile with additional information for request (compile flags). They must
-- be a set as script flags in right order (last parameter not required, so if not set will be set empty string). All
-- buffer data must be put in standard input
--
local socket_factory = require("socket")
local cjson = require("cjson")

local function main()
  local host = arg[1]
  local port = arg[2]
  local additional_info_filename = arg[3]

  if host == nil or port == nil then
    error("you must set host as first argument and port as second")
  end

  local additional_info = ""
  if additional_info_filename ~= nil then
    local file = io.open(additional_info_filename, "r")
    additional_info = file:read("*a")
    file:close()
  end

  local sock = socket_factory.tcp()
  sock:connect(host, port)

  local input = io.read("*a")

  local request = cjson.encode{0, {
    version = "v1",
    id = 0,
    buf_type = "cpp",
    buf_name = "a.cpp",
    buf_body = input,
    additional_info = additional_info,
  }}

  local ok, err = sock:send(request .. "\n")
  if not ok then
    error(err)
  end

  local str, err1 = sock:receive("*l")
  if not str then
    error(err1)
  end

  print(str)
end

main()
