#!/bin/lua

-- @script simple client for hls-server (cpp)
--
-- @usage you need set host, port and name offile with additional information for request (compile flags). They must
-- be a set as script flags in right order (last parameter not required, so if not set will be set empty string). All
-- buffer data must be put in standard input
--
-- @usage `./simple_hl_client 127.0.0.1 9173 < a.cpp`
--
local socket_factory = require("socket")
local cjson = require("cjson")

local function main()
  local host = "localhost"
  local port = arg[1]
  local additional_info_filename = arg[2]

  if host == nil or port == nil then
    error("you must set port as first argument")
  end

  local additional_info = ""
  if additional_info_filename ~= nil then
    local file = io.open(additional_info_filename, "r")
    additional_info = file:read("*a")
    file:close()
  end

  local sock = socket_factory.tcp()
  sock:connect(host, port)

  local input = io.read("*a")

  local request = cjson.encode{0, {
    version = "v1.1",
    id = "controll",
    buf_type = "cpp",
    buf_name = "a.cpp",
    buf_body = input,
    additional_info = additional_info,
  }}

  local ok, err = sock:send(request .. "\n")
  if not ok then
    error(err)
  end

  local str, err1 = sock:receive("*l")
  if not str then
    error(err1)
  end

  print(str)
end

main()
